question_bank = [
    {"question": "What color is snail blood?", "answer": "blue"},
    {"question": "How many hearts does an octopus have?", "answer": "three"},
    {"question": "What fruit was once banned in France?", "answer": "tomato"},
    {"question": "Which animal can sleep for three years?", "answer": "a snail"},
    {"question": "What is the world's smallest mammal?", "answer": "the bumblebee bat"},
    {"question": "How many bones are in the human body at birth?", "answer": "approximately 270"},
    {"question": "What is a group of flamingos called?", "answer": "a stand"},
    {"question": "Which planet rains diamonds?", "answer": "Saturn"},
    {"question": "What did ancient Egyptians use as toothpaste?", "answer": "crushed ashes and eggshells"},
    {"question": "What is the only bird that can fly backwards?", "answer": "the hummingbird"},
    {"question": "How many elements are in the periodic table?", "answer": "118"},
    {"question": "What is the largest organ in the human body?", "answer": "the skin"},
    {"question": "What creature has the most powerful bite?", "answer": "the saltwater crocodile"},
    {"question": "Which animal's milk is pink?", "answer": "the hippo"},
    {"question": "What is the average lifespan of a taste bud?", "answer": "10 to 14 days"},
    {"question": "What was the first animal in space?", "answer": "a dog named Laika"},
    {"question": "What country has no rivers?", "answer": "Saudi Arabia"},
    {"question": "How long can a cockroach live without its head?", "answer": "up to a week"},
    {"question": "What is the world's longest-living animal?", "answer": "the Greenland shark"},
    {"question": "What was the first video game?", "answer": "Tennis for Two"},
]
